### ISSUE TITLE
Adding shellHook for the nix-shells

### ISSUE THREAD

**Issue by SFrijters** [ElvishJerricco/reflex-project-skeleton#12]
To work with postgresql-simple I've added `pkgs.postgresql` to the tools attribute as per the example in reflex-platform/project/default.nix, so that the PostgreSQL binaries are available, but I would also like to have the server start automatically when I go into a nix-shell. To this end I've tried to add a shellHook to the derivation for the shell, but I've failed miserably so far.
Is it necessary to edit reflex-platform/project/default.nix to (somehow) accept shellHook as an attribute, or is there another way? I've also tried to make a shell.nix and use shells.ghc as a buildInputs for mkDerivation, but this gives me a very useless error...

```nix
{ nixpkgs ? import <nixpkgs> {}}:

let
  inherit (nixpkgs) pkgs;
  shell-ghc = (import ./default.nix {}).shells.ghc;
in
  pkgs.stdenv.mkDerivation rec {
  name = "db-ghc";
  buildInputs = [ shell-ghc ];
  shellHook = ''
    NIX_SHELL_NAME=${name}
  '';
}
```
```
$ nix-shell
these derivations will be built:
  /nix/store/rscajj1kpiimp7drswyrpfb0lcny9cpm-shell.drv
building '/nix/store/rscajj1kpiimp7drswyrpfb0lcny9cpm-shell.drv'...
builder for '/nix/store/rscajj1kpiimp7drswyrpfb0lcny9cpm-shell.drv' failed to produce output path '/nix/store/68sklav05wk0qjs42psdxr16hhiy46b7-shell'
error: build of '/nix/store/rscajj1kpiimp7drswyrpfb0lcny9cpm-shell.drv' failed
```
Any help would be appreciated.

**Comment by ElvishJerricco** [comment]
The error there is because `shells.ghc` isn't actually a derivation that builds any output, so `nix-build`'ing it will fail just as you saw here. Maybe it ought to, but that wouldn't be useful in this case; adding it as a `buildInput` won't add *its* build inputs to the shell. You might have better luck with `overrideAttrs`.

```nix
(import ./. {}).shells.ghc.overrideAttrs (old: {
  shellHook = ''
    ${old.shellHook or ""}
    NIX_SHELL_NAME=db-ghc
  '';
})
```

`overrideAttrs` is a function that exists on most derivations that allows you to re-configure the arguments that said derivation passed to `stdenv.mkDerivation`. You pass it a lambda that takes the old config as an argument and returns new attrs to override with. In this case, we're overriding `shellHook` with a string that has the old shell hook (or "" if there was none) followed by your `NIX_SHELL_NAME` line.

---

I'd caution you against having the shell hook do anything crazy like launching a Postgres instance. Shells are largely assumed to be pure (I'm not even sure the shellHook knows the user's working dir), but launching a stateful server is inherently impure. Plus, I know I personally end up re-entering nix-shells quite often in other terminals or whatnot.

You might want to look at Obsidian's [gargoyle](https://github.com/obsidiansystems/gargoyle), which lets your backend start up the PG server and ensures proper sharing between backend instances and proper shutdown. Otherwise I'd just look for the most convenient ways of starting up a PG server manually. I personally like creating `nixos-container`s that have the DB I need, that way I can just do `nixos-container start my-db` to get it up again.

**Comment by SFrijters** [comment]
Thanks for the solution and the tips for handling my use case better - I'll look into those. At least I'll get my shell name in my prompt :+1:

I was actually close to your solution, but I was using override instead of overrideAttrs. Nix is lovely when it works but it's a steep learning curve imo...
