### ISSUE TITLE
Nix installs massive file store; fail to notice changes in code

### ISSUE THREAD

**Issue by willosborne** [ElvishJerricco/reflex-project-skeleton#19]
I've followed the setup instructions, but the first time I build it nix installs a MASSIVE set of files, well over 20gb, in nix store. 
Looking at the "copying path" stuff it's dumping in the terminal, it's installing some really weird things like LLVM, ncurses, openjdk
Are all of these for the android build, and if so, how do I prevent this? 

Also, I copied my code and project structure to a new directory to try again, and it wasn't noticing any changes in my code with the ./cabal-ghcjs script (just saying "Up to date") - when I ran nix-build it re-downloaded all the stuff from earlier!

Any idea what's wrong?

**Comment by ElvishJerricco** [comment]
1. What does your `default.nix` look like?
2. Can you give us the output of `nix-shell -p nix-info --run "nix-info -m"`?

**Comment by willosborne** [comment]
Thanks so much for your help! I've never really used Nix before, and I'm here for GHCJS via Reflex because Stack's support is so bad.

`default.nix`:
```
{ reflex-platform ? import ./reflex-platform {} }:

reflex-platform.project ({ pkgs, ... }: {
  packages = {
    common = ./common;
    backend = ./backend;
    frontend = ./frontend;
  };

  android.frontend = {
    executableName = "frontend";
    applicationId = "org.example.frontend";
    displayName = "Example Android App";
  };

  ios.frontend = {
    executableName = "frontend";
    bundleIdentifier = "org.example.frontend";
    bundleName = "Example iOS App";
  };

  shells = {
    ghc = ["common" "backend" "frontend"];
    ghcjs = ["common" "frontend"];
  };
})
```
Running `nix-shell -p nix-info --run "nix-info -m"` downloaded a further 300mb of stuff including gcc and bash-interactive, but gave me this:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-36-generic, Ubuntu, 16.04.4 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(will): `"nixpkgs-19.03pre155767.8070a6333f3"`
 - nixpkgs: `/home/will/.nix-defexpr/channels/nixpkgs`
```

**Comment by ElvishJerricco** [comment]
Yea, so by defining the `android` and `ios` sections, you are saying that when you do `nix-build`, you want it to download the mobile toolchain and build mobile apps (Android building is only supported on Linux and iOS building is only supported on macOS, so for you this only does the Android build). The mobile toolchains can be quite large, so that would explain the amount of space you're seeing used. If you don't want it to get the Android / iOS toolchains, you'll have to either removes those sections, or specify the builds you want manually, like `nix-build -A ghcjs.frontend`.

That said, even just the standard GHC and GHCJS builds take a good amount of space (8G, I think?). This is because Nix pins down *all* dependencies to Nix versions, including the C compiler and all system libraries.

**Comment by willosborne** [comment]
Hey I'm so sorry - been away so just saw this now! That makes sense - so it's safe to delete the IOS and android bits. That's really helpful :) 

Do you have any idea how to fix the cabal-ghcjs script not finding changes problem?

**Comment by willosborne** [comment]
I've figured out the issue - it was problems with my frontend's .cabal file. I think this resolves all my issues - thanks again for all your help!
